ALTER TABLE "Date_Dim"
ALTER COLUMN "Year" TYPE INTEGER,
ALTER COLUMN "Quarter" TYPE INTEGER,
ALTER COLUMN "Month" TYPE INTEGER;

ALTER TABLE "Time_Dim"
ALTER COLUMN "Hour" TYPE INTEGER,
ALTER COLUMN "Minute" TYPE INTEGER,
ALTER COLUMN "Second" TYPE INTEGER;
